languageCode = 'en-us'
baseURL='https://themyth.dev'
title = "Myth's Blog"
theme = 'lugo'
datesinlist = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            # Render <sup> tags
            unsafe = true
